[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = ["server/build/**"]